### ISSUE TITLE
Support basic NickServ commands

### ISSUE THREAD

**Issue by postmodern** [sstephenson/hector#37]
It's a bit awkward to authenticate using a server password. Supporting `NickServ identify` might be nicer?

**Comment by raws** [comment]
Hector is meant to be a simple private chat server for small groups who are comfortable using IRC. Allowing clients to connect anonymously in order to use a NickServ service would also require support for channel access controls and probably other sources of complexity.

While it's certainly possible to write your own Hector identity adapter that accepts anonymous connections, and a Hector service to act as NickServ, a more traditional ircd might be a better fit for your needs.

(Also, apologies for the tardy response!)
