### ISSUE TITLE
Implement WHO

### ISSUE THREAD

**Issue by sstephenson** [sstephenson/hector#4]

**Comment by clintecker** [comment]
I think I shall work on this

**Comment by clintecker** [comment]
https://github.com/clintecker/hector/commit/fc91e8a0a12e579fc768f487f62a27e9c1ec5358

Here's my commit, the message should describe it pretty well.  Since the 352's pass along "Real Name" i needed to start storing realname somewhere, so we do that on the session object.  That's why I had to alter all the Session.create calls all over the place.

If someone /WHO's an invalid or empty channel, it just returns the 315 end of WHO, and for real channels with people it obviously lists everyone out, 1 per line with 352s.

I added 3 tests, 1 for sending a /who to an invalid channel, 1 for sending a /who to a channel you've joined and one for sending a /who to a channel with people in it that you haven't joined.
