### ISSUE TITLE
Implement channel access controls

### ISSUE THREAD

**Issue by clintecker** [sstephenson/hector#5]
This is kind of a big thing, but it would entail Hector talking to some sort of relational database to store persistant channel permissions.  Ultimately I believe usernames and passwords themselves would be stored here.

Probably the easiest solution would be to use sqlite.

**Comment by raws** [comment]
I would probably implement channel access controls as `authorize(username)` on `Hector::Identity.adapter`.

In fact, even though channel access controls seem out of Hector's proper scope, Hector's default `YamlIdentityAdapter` could simply return `true` for everyone, leaving finer-grained controls for others to implement.

P.S. I know this issue is hella old and nobody except for Clint cares about it. I just happened to be looking at the list. Don't judge!

**Comment by clintecker** [comment]
:+1:

You would be passing in username + channel, though, right?

**Comment by raws** [comment]
Hmm, yeah. `authorize_join(username, channel)` or something. I can envision other `authorize_` methods for decidedly un-Hector-like events such as kicking, opping, or even sending messages.

**Comment by clintecker** [comment]
How.... primitive.

**Comment by raws** [comment]
Your _face_ is primitive

**Comment by clintecker** [comment]
hm!!

**Comment by raws** [comment]
GitHub is racist against eggplants and refuses to let me post one

**Comment by jyotty** [comment]
I think you mean AUBERGINE

GOD
